### ISSUE TITLE
Not able to set cursor size

### ISSUE THREAD

**Issue by vpont** [phisch/phinger-cursors#1]
First of all, great job!

I've been using [Breeze](https://aur.archlinux.org/packages/breeze-default-cursor-theme/) for a long time and it's nice to se a similar but improved one!

However, for some reason I've not been able to set the cursor size. With Breeze all I had to do in `~/.Xresources` was:
```
Xcursor.theme: Breeze_Default
```
And the cursor looked fine no matter what resolutions or dpi (I use up to three different, depending on the screens I'm using).

I've tried with:
```
Xcursor.theme: phinger-cursors
Xcursor.size: 24
```
Both 24 and 32 look too small and identical (like it's 16x16). But setting it to 48 looks too big ...
Any hints? Thank you!

**Comment by phisch** [comment]
@vpont can you link the source of the `Breeze_Default` theme please? I can have a look at which sizes they provide to compare.
The sizes provided by phinger-cursors should be more than enough to pick from.

**Comment by vpont** [comment]
The link to the aur is already in my 1st post

**Comment by phisch** [comment]
@vpont Just figured, sorry.

That cursor theme provides cursors at a size of 40: 
![image](https://user-images.githubusercontent.com/1282767/151137848-fca40bc6-aff7-4b01-b795-808acffdca5b.png)

I haven't seen that in other cursor themes yet, and I am not sure which DPI this is targeted for. I already designed each icon for phinger-cursors at a base grid of 24 and 32, adding and maintaining another one on base grid 20 would be way too much work for too little return.

If 32 is too small and 48 is too big, you are unfortunately out of luck. I'm sorry!

**Comment by phisch** [comment]
@vpont there actually was a bug where cursors contained wrong sizes. Please update to https://github.com/phisch/phinger-cursors/releases/tag/v1.1 and let me know if this also solves your issue!

**Comment by vpont** [comment]
I knew there was something wrong with some icon sizes! :smile: 
Now I can see the difference between 32, 48, etc. I'm still missing size 40 but I'm just going to set different cursor sizes for each screen resolution. Thanks anyway!

**Comment by phisch** [comment]
I'm glad it helps at least a bit! :+1:
