### ISSUE TITLE
Add `pirate` as an alias of `kill`

### ISSUE THREAD

**Issue by InternetUnexplorer** [phisch/phinger-cursors#10]
I noticed that, among other things, KWin [uses the `pirate` cursor for its "Kill Window" action](https://github.com/KDE/kwin/blob/d7ee3f12211286537aa6614cd1893c4c78df40f9/src/killwindow.cpp#L46).

Would it be possible to add a symlink from `pirate` to the `kill` icon? Thanks! :)

**Comment by phisch** [comment]
I thought I already did that. Will add this symlink for the next release!

**Comment by InternetUnexplorer** [comment]
Thanks a bunch! :)

**Comment by phisch** [comment]
Although this is not in the [2.0-beta.1 release](https://github.com/phisch/phinger-cursors/releases/tag/v2.0-beta.1), I have already added this alias to the Figma file, so it will be included in the stable, or next beta release!

Thanks again for reporting this, and sorry for the wait!

**Comment by phisch** [comment]
Already in the `2.0-beta.2` release!
