### ISSUE TITLE
Add alias `dnd-copy` and `dnd-ask` for Gnome

### ISSUE THREAD

**Issue by Skunkietronic** [phisch/phinger-cursors#11]
Hi there,

I noticed the copy and ask cursors in Gnome 41 were missing, just need to add the symlinks `dnd-copy` to `copy` and `dnd-ask` to `help`, and all works well.

Thanks for such a wonderful cursor set.

**Comment by phisch** [comment]
Sorry for the wait. But as far as I can tell, one of the last Gnome releases has cleaned up a lot of their cursor mess. And this should not be necessary anymore. Can you check if this still happens on the latest Gnome version with the [2.0-beta.1 release](https://github.com/phisch/phinger-cursors/releases/tag/v2.0-beta.1) I published earlier?

**Comment by phisch** [comment]
Tested this on the latest GNOME version and that version seems to just use copy and help. Added the 2 aliases to the Figma document regardless. So they will be available in the next beta or stable release.

Thanks for the report!
