### ISSUE TITLE
Blurry on 150%, no 36px size

### ISSUE THREAD

**Issue by Andrei9383** [phisch/phinger-cursors#17]
Because there is no size 24*1.5=36 the cursor looks slightly blurry on 150% scaling. Tested on KDE

**Comment by phisch** [comment]
There are differences in how desktop environments load the cursor images when scaling is applied. Most take your requested size, for example 24, multiply it by the scale, in your case `24 * 1.5 = 36`, and then they request the closest cursor to that size, which in this case would load sprites with a size of 32.

What you describe is something I have notices in some applications, where they intentionally load a larger cursor, so in that case it would load the `48px` sprites, and they scale that down to the size they calculate earlier.

There isn't really anything I can do against that, it's just a horrible implementation on their side. But what you can try is to figure out how they do this, and pick a size that results in them not scaling manually.

For example, if you request a cursor at the size of `32`, they multiply it by `1.5`, which comes out to `48`, which is an available sprite size in this theme, so it would not get scaled by them. Essentially, pick `<AVAILABLE_SIZE>/150*100` as your size.

I hope this information helps. Feel free to keep this conversation up, but there isn't anything I can do to mitigate that, except introducing another base scale to re-design all cursors for, and I'm not planning on doing that.
