### ISSUE TITLE
Red dot on SVG's

### ISSUE THREAD

**Issue by sentakuhm** [phisch/phinger-cursors#18]
is there any way to remove red dots from SVGs, i am using hyprland's hyprcursor which is uses SVGs directly not png, but red dot on SVG realy annoying.
![swappy-20240513-133427](https://github.com/phisch/phinger-cursors/assets/25133437/459c7de0-90d4-47ae-8ffa-5a21e3856ed0)

**Comment by phisch** [comment]
They are optionally used by the [build system](https://github.com/phisch/cursor-theme-builder) I wrote. It uses the middle of that element as the hotspot, and removes it. It can even be animated, though I'm not leveraging that right now.

The figma document used is available in this repository (check in the root). You can hide the `hotspot` component, and then export the sprites as SVGs without it. Or you go through all sprites that are available in this repository and remove them by hand.

**Comment by sentakuhm** [comment]
thank you!
