### ISSUE TITLE
Cursor disappears in GIMP

### ISSUE THREAD

**Issue by Strongleong** [phisch/phinger-cursors#19]
As title says: there is no cursor when I hover over GIMP. Cursor appears in some situations, i.e. when cursor hover dock border (resizing cursor), or when  hover over  text input (text input curosr), this is pretty much every situation where cursor exists

P.S. Sorry for bad English

**Comment by phisch** [comment]
I can't reproduce this:

https://github.com/phisch/phinger-cursors/assets/1282767/9f04f78b-b5e4-4cde-8df0-b4bb95ac4f82

Which version of GIMP do you use, and what's your desktop environment?

**Comment by Strongleong** [comment]
Strangely, when I tried to record with obs cursor behavior I restarted my pc and now everything works as expected :sweat_smile: 

Sorry for disturbing you 

P.S. Hyprland 0.39.1 and GIMP 2.10.36
