### ISSUE TITLE
Transparent borders

### ISSUE THREAD

**Issue by BeeverFeever** [phisch/phinger-cursors#22]
I love the theme but I was wondering if it is possible to not use the transparent borders? I don't know if it is just my setup somehow but they dont have enough contrast for me and I find it hard to see the cursor. If it's not possible all good.

**Comment by phisch** [comment]
You could create your own version/fork. The figma file is available in this repository, and the build system (mentioned in the readme) is used in this [workflow](https://github.com/phisch/phinger-cursors/blob/master/.github/workflows/main.yml).
