### ISSUE TITLE
Wrong icon orientation for row-resize_24

### ISSUE THREAD

**Issue by Nemric** [phisch/phinger-cursors#23]
I think that row-resize_24.svg is in wrong orientation as it is the same as col-resize_24.svg

**Comment by phisch** [comment]
Wow, nice catch! I'll fix this for an update pretty soon!

**Comment by phisch** [comment]
Fixed in [release v2.1](https://github.com/phisch/phinger-cursors/releases/tag/v2.1), thanks again for reporting!

**Comment by Nemric** [comment]
You're welcome, I did install the fix but can't remember the software in which the error occurred :D
Thanks :)
