### ISSUE TITLE
Cursor outlines are very dark

### ISSUE THREAD

**Issue by aaravrav** [phisch/phinger-cursors#26]
The cursor outlines are dark and make the cursor not stand out against the background and also has the side effect of making them look blurry. This is probably because they are not fully opaque.

For Phinger Cursors (Dark)

**Comment by phisch** [comment]
This is by design, see #22 for a tip on how to create your own fork.

**Comment by BeeverFeever** [comment]
I have  [forked](https://github.com/BeeverFeever/phinger-cursors-white-borders) the repo and changed the borders to be fully opaque. Please note, my fork is not officially endorsed and I do not plan on keeping it up to date with every commit, only the major releases. Also @phisch I can delete this comment if you wish.
