### ISSUE TITLE
This cursor is amazing, please add more colors.

### ISSUE THREAD

**Issue by garare992** [phisch/phinger-cursors#27]
This cursor is amazing, please add more colors. Red, magenta, yellow, brown, etc.

**Comment by phisch** [comment]
Do you mean color variants, where the entire cursor has different colors?

**Comment by garare992** [comment]
> Do you mean color variants, where the entire cursor has different colors?

Yes! :+1:

**Comment by phisch** [comment]
I don't plan on building color variants myself. But you can relatively easily fork this repository, update the figma document and build your own color variants. There should be enough information about the build process and system in the readme.
