### ISSUE TITLE
Doesn't scale

### ISSUE THREAD

**Issue by EchoesForeAndAft** [phisch/phinger-cursors#3]
Very nice cursors, but they don't scale at all. (Tested on KDE Plasma 5.23). The cursors are perfectly legible on my right-side 1080p monitor, but on my left-hand 1440p monitor they're tiny.

**Comment by phisch** [comment]
As far as I know, this is a feature of your DE. There is nothing special a cursor theme can do for this. Phinger cursors provides 6 sizes, so your DE has more than enough sizes to pick from.
