### ISSUE TITLE
ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by Rishabh672003** [phisch/phinger-cursors#4]
error while installing from aur -
> ==> Validating source files with md5sums...
    phinger-cursors-variants.tar.bz2 ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: phinger-cursors 
	 context: exit status 1 
> ==> Making package: phinger-cursors 1.1-1 (Wednesday 26 January 2022 11:19:07 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found phinger-cursors-variants.tar.bz2
==> Validating source files with md5sums...
    phinger-cursors-variants.tar.bz2 ... FAILED
==> ERROR: One or more files did not pass the validity check!
 -> error making: phinger-cursors

**Comment by Wiichele** [comment]
If you use `paru` remove the cache with `paru -Sc` and update like normal

**Comment by phisch** [comment]
Thanks for the report. I updated the PKGBUILD to include the version in the downloaded file, so it doesn't collide with old cached versions anymore. This won't be an issue in the future again!

https://aur.archlinux.org/cgit/aur.git/commit/?h=phinger-cursors&id=5dcd57cb700d1540d431b45d5505c34a1acd3605
