### ISSUE TITLE
Cursor size is inconsistent

### ISSUE THREAD

**Issue by D3SOX** [phisch/phinger-cursors#6]
Hey,

I like the design of Phinger, but I have a problem with the cursor size.

For me, Breeze Light at size 24 has the perfect size.
Phinger Light at size 24 is too small (especially the normal cursor) and size 32 is too big (especially the resize and text cursors).

I'm using KDE Plasma 5.23.90 on Arch <sub>btw</sub> using the AUR package version 1.1-3.

---

Breeze Light, Size 24:

Normal
![image](https://user-images.githubusercontent.com/24937357/151937491-3040888b-7ac6-4ecb-a60a-52e712f7e81a.png)
Text
![image](https://user-images.githubusercontent.com/24937357/151937415-37cb6790-4aae-4ae5-86d3-944c805c5bb0.png)
Resize
![image](https://user-images.githubusercontent.com/24937357/151937380-42db03c1-1629-4ce8-8d7f-cd885f61d441.png)

---

Phinger Light, Size 24:

Normal
![image](https://user-images.githubusercontent.com/24937357/151937587-4ca17020-1617-4e54-b8a5-4dfe5b2f5312.png)
Text
![image](https://user-images.githubusercontent.com/24937357/151937630-f795cbe5-4b94-4fc3-be11-1a7267dc230b.png)
Resize
![image](https://user-images.githubusercontent.com/24937357/151937668-1accb5c0-08af-4436-8976-82a139dd65ab.png)

---

Phinger Light, Size 32

Normal
![image](https://user-images.githubusercontent.com/24937357/151937820-aa2b5af8-6d97-4ad0-bf0c-b71601557188.png)
Text
![image](https://user-images.githubusercontent.com/24937357/151937846-f40ab65a-89ca-476e-856d-09b81e2b97e2.png)
Resize
![image](https://user-images.githubusercontent.com/24937357/151937864-ae6023b5-5ec9-4dc6-82c9-e1e6d0a41af7.png)

---

<details>
<summary>Off-topic</summary>

(is it named Phinger because of the word finger? xD)
</details>

**Comment by D3SOX** [comment]
In the resize example, I used Konsole.
I compared it again and the text cursor is actually good. It's just a little smaller at 24 compared to Breeze at 24.

**Comment by D3SOX** [comment]
![image](https://user-images.githubusercontent.com/24937357/151956229-c8817278-c093-4d47-bf08-404bfd8bb85c.png)

Maybe unrelated to this, but I also noticed that the preview in Plasma's system settings doesn't show the pointer with the spinner.

**Comment by phisch** [comment]
@D3SOX the spinner is related to #5 but in your screenshot the fleur cursor seems to be the wrong one as well.
I was expecting a couple aliases to be missing, i didn't have too many people testing the theme during beta. No big deal.

For the 24x24 cursor, there isn't much space to make it bigger:
![image](https://user-images.githubusercontent.com/1282767/151963747-bae420f0-38a7-4b42-8338-5c0efe1b90e3.png)

**Comment by D3SOX** [comment]
I meant the size of the default cursor without anything else.

**Comment by phisch** [comment]
I get it, but I need to leave that space empty in the default cursor, so when the "loading" cursor for example gets displayed, the cursor size doesn't suddenly switch. It should look like something was added to your cursor, and not like your cursor switched to a different sized one.

**Comment by phisch** [comment]
@D3SOX The new [2.0-beta.1 release](https://github.com/phisch/phinger-cursors/releases/tag/v2.0-beta.1) has some changes to better utilize the available space. I'd love it if you can have a look and test to see if you are more happy with the cursor sizes now!

Here is an example (green dot means this is new, the other is old):
![image](https://github.com/phisch/phinger-cursors/assets/1282767/5936da80-fcd5-4d3f-b5bd-4ce6484ac4f4)

Let me know what you think!

**Comment by phisch** [comment]
The previews on plasma are also looking nice now:
![Screenshot_20240407_005646](https://github.com/phisch/phinger-cursors/assets/1282767/3e9d269a-051b-4a02-a5f7-8db865dfda31)
